esphome:
  name: ble_rgb_light
  libraries:
    - "BLE"

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_hostname
  password: !secret wifi_password
  ap:
    ssid: "BLERGB Fallback"
    password: "fallbackpass"

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

logger:

api:

ota:
  platform: esphome

external_components:
  - source: components
  # - source:
  #     type: git
  #     url: https://github.com/esphome/esphome
  #     ref: dev
  #   components: [ BLE ]

light:
  - platform: ble_rgb_light
    name: BLE RGB Light
    id: my_ble_light
    output: output_component1

output:
  - platform: template
    id: output_component1
    type: float
    write_action:
    #dummy output to satisfy light output requirement
      - lambda: |-
          // Do nothing
          return;